[versions]
kotlin = "1.9.10"

mockk =  "1.13.8"
kotest = "5.7.2"

ktlint-plugin = "0.50.0"
ktlint-integration = "11.6.0"
detekt = "1.23.1"

[libraries]

kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]

ktlint-integration = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-integration" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[bundles]

testing = [
    'kotest-runner',
    'mockk',
]
